const FACTORY_MODULE = 'factory';
const ROUTER_MODULE = 'router';
const PAIR_MODULE = 'pair';
const LIBRARY_MODULE = 'library';
const RESOURCE_ACCOUNT = '0xbe9c218a7a8fa9a176f55362111b1a41863acfc6d740d19441d2216c06bafd9d'

export const V2_FACTORY_AADDRESS = `${RESOURCE_ACCOUNT}::${FACTORY_MODULE}`;
export const V2_ROUTER_ADDRESS = `${RESOURCE_ACCOUNT}::${ROUTER_MODULE}`;
export const V2_PAIR_ADDRESS = `${RESOURCE_ACCOUNT}::${PAIR_MODULE}`;
export const V2_LIBRARY_ADDRESS = `${RESOURCE_ACCOUNT}::${LIBRARY_MODULE}`;